id: P004579
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W447
  title: གསུང་འབུམ། བློ་གྲོས་རྒྱལ་མཚན
  author: ''
  volumes:
    947ab4ea8e5140d4ad0c6087f3a132fa:
      image_group_id: I6461
      title: ''
      volume_number: 1
      total_pages: 530
      base_file: v001.txt
    5fab6f0d09fc431c8862e5048b056824:
      image_group_id: I6462
      title: ''
      volume_number: 2
      total_pages: 518
      base_file: v002.txt
    942285a9e76c4c678f1ebfe52aea0286:
      image_group_id: I6463
      title: ''
      volume_number: 3
      total_pages: 592
      base_file: v003.txt
    4bb3e4e0a5d249699d8afb9996cda36d:
      image_group_id: I6464
      title: ''
      volume_number: 4
      total_pages: 514
      base_file: v004.txt
    853c8e222beb4d4ba7bb5fb58ffc5b81:
      image_group_id: I6465
      title: ''
      volume_number: 5
      total_pages: 548
      base_file: v005.txt
