id: I39CF94F7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T10:03:33+00:00'
last_modified: '2022-06-08T02:04:30.365339+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W447
  title: གསུང་འབུམ། བློ་གྲོས་རྒྱལ་མཚན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    45FD:
      image_group_id: I6461
      title: ''
      total_pages: 530
      order: 1
      base_file: 45FD.txt
    A68C:
      image_group_id: I6462
      title: ''
      total_pages: 518
      order: 2
      base_file: A68C.txt
    '9948':
      image_group_id: I6463
      title: ''
      total_pages: 592
      order: 3
      base_file: 9948.txt
    EC1D:
      image_group_id: I6464
      title: ''
      total_pages: 514
      order: 4
      base_file: EC1D.txt
    39F0:
      image_group_id: I6465
      title: ''
      total_pages: 548
      order: 5
      base_file: 39F0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
