id: I39CF94F7
legacy_id: P004579
ocr_import_info:
  bdrc_scan_id: W447
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T09:59:16'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T18:05:11.325570+00:00'
last_modified: 2022-09-04 02:06:32.773596
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W447
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW447
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་གྲོས་རྒྱལ་མཚན།
  author: སྤྱན་སྔ་བློ་གྲོས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.5890016291473295
  ocr_word_median_confidence_index: 0.5899999737739563
quality: null
bases:
  I6462:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6462
      total_pages: 518
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I6462.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5674585695822132
    legacy_id: v002
  I6461:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6461
      total_pages: 530
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6461.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5886642988730122
    legacy_id: v001
  I6464:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6464
      total_pages: 514
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I6464.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5758348776106087
    legacy_id: v004
  I6463:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6463
      total_pages: 592
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I6463.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.596375205150746
    legacy_id: v003
  I6465:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6465
      total_pages: 548
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I6465.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.608316456463098
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
